import type { Metadata } from 'next'
import './bootstrap.css'
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="tw-font-arial container">{children}</body>
    </html>
  )
}
